import { CDN_URL } from "../utils/constants";


const RestaurantCard = (props) => { 
    const {resData} = props;
    const {cloudinaryImageId, name, cuisines , avgRatingString, sla: {deliveryTime}} =resData?.info;
    // following the best practices here --> directly destructuring it and using as a variable 
    //  ? here is the optional chanining 
      return ( 
        <div className="res-card p-4 m-4 w-[200px]" style={{backgroundColor: "babypink"}}>  
        {/* note: Resturnt card is a react compopnent it reutrns jsx we are using 2 brackets  bcz 1st one is bcz of putting js inside the jsx and
        the 2nd one is for passing the object literals 
        
        here I have given the width of 200px -> this is the manual option to give the width this is actually giving the dynamic classes to css*/}
            <img
              className="res-logo"
              alt="res-logo"
              src={
                    CDN_URL
                    + resData.info.cloudinaryImageId
              }
              />
                  {/* // here we are dinamically changing the img with the data from resObj
                  all the images are hosted on the cdn and we are using these cdn links to get the image  */}
               
               {/* we are adding the cloudinary id to the url --> this is js code hence for that we need to put the curly braces  */}
               {/* inside the course swiggy is using the cloudinary cdn {css} but while we are feting the information we are not getting it -- instead we have half pf the link and 
               rest of the cloudinary imag will be generated by adding the id to it -- by changing the id we can generate other img */}
               <h1>{name}</h1>  
              
              {/* join here is used to seperate the cuisines with comma */}
               <h4>{cuisines.join(",")}</h4> 
                <h4>{avgRatingString}</h4> 
               <h4>{deliveryTime} minutes</h4>  
              
               {/* carefully check the api given who is umder what  */}
              {/* <h4>{resData.info.costForTwo}</h4> */} 
        </div>
      );
  };
  
  /*does here [ResturantCard] the style refers to the css style ?, this res-card is showing all the resturants and display all its properties ,l have doubt like I need to create the blocks 
  so that it will contain all the returants list , how can we create them ? */
  /* we are adding style card, in react if we want to style things that to inline than we need to pass the js object */
  /* we can also write the style like style = {{backgroundcolo: red}} --> this is telling that 1st bracket is js */

  export default RestaurantCard;